sudo: false

dist: trusty

language: c
compiler:
  - gcc
env:
  - PY=2

cache:
  directories:
  - $HOME/an

script:
  - /bin/bash build_astrometry.sh
addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - netpbm
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - libgsl0-dev